# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

cluster_NUTS2_solar_q2qv1:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cluster/q2q_onwind_cluster_NUTS2_v1.pkl
      solar: data_ES/q2q/cluster/q2q_solar_cluster_NUTS2_v1.pkl

cluster_NUTS2_solar_q2qv2:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cluster/q2q_onwind_cluster_NUTS2_v2.pkl
      solar: data_ES/q2q/cluster/q2q_solar_cluster_NUTS2_v2.pkl

cluster_NUTS2_solar_q2qv3:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cluster/q2q_onwind_cluster_NUTS2_v3.pkl
      solar: data_ES/q2q/cluster/q2q_solar_cluster_NUTS2_v3.pkl


