# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers



onwindWT_1500_solar_q2qNo:
  renewable:
    onwind:
      resource:
        turbine: Suzlon_S82_1.5_MW

onwindWT_1750_solar_q2qNo:
  renewable:
    onwind:
      resource:
        turbine: Vestas_V66_1750kW

onwindWT_2000_solar_q2qNo:
  renewable:
    onwind:
      resource:
        turbine: Vestas_V80_2MW_gridstreamer

onwindWT_2300_solar_q2qNo:
  renewable:
    onwind:
      resource:
        turbine: Siemens_SWT_2300kW

onwindWT_4000_solar_q2qNo:
  renewable:
    onwind:
      resource:
        turbine: NREL_ReferenceTurbine_2020ATB_4MW



