# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

name: Q2Q_repository
channels:
- conda-forge
dependencies:
- python>=3.10
- pandas>=2.1
- matplotlib
- ipykernel
- scipy
- xarray

