
cutout_europe2019_solar-hsat_q2qv1:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_europe2019_v1.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_europe2019_v1.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2019.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2019.csv
  snapshots:
    start: "2019-01-01"
    end: "2020-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2019 or DateOut != DateOut)
  atlite:
    default_cutout: europe-2019-sarah3-era5

cutout_europe2019_solar-hsat_q2qv2:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_europe2019_v2.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_europe2019_v2.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2019.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2019.csv
  snapshots:
    start: "2019-01-01"
    end: "2020-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2019 or DateOut != DateOut)
  atlite:
    default_cutout: europe-2019-sarah3-era5

cutout_europe2019_solar-hsat_q2qv3:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_europe2019_v3.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_europe2019_v3.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2019.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2019.csv
  snapshots:
    start: "2019-01-01"
    end: "2020-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2019 or DateOut != DateOut)
  atlite:
    default_cutout: europe-2019-sarah3-era5





cutout_europe2020_solar-hsat_q2qv1:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_europe2020_v1.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_europe2020_v1.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2020.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2020.csv
  snapshots:
    start: "2020-01-01"
    end: "2021-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2020 or DateOut != DateOut)
  atlite:
    default_cutout: europe-2020-sarah3-era5

cutout_europe2020_solar-hsat_q2qv2:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_europe2020_v2.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_europe2020_v2.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2020.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2020.csv
  snapshots:
    start: "2020-01-01"
    end: "2021-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2020 or DateOut != DateOut)
  atlite:
    default_cutout: europe-2020-sarah3-era5

cutout_europe2020_solar-hsat_q2qv3:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_europe2020_v3.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_europe2020_v3.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2020.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2020.csv
  snapshots:
    start: "2020-01-01"
    end: "2021-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2020 or DateOut != DateOut)
  atlite:
    default_cutout: europe-2020-sarah3-era5





cutout_iberia2019_solar-hsat_q2qv1:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2019_v1.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2019_v1.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2019.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2019.csv
  snapshots:
    start: "2019-01-01"
    end: "2020-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2019 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2019-era5

cutout_iberia2019_solar-hsat_q2qv2:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2019_v2.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2019_v2.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2019.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2019.csv
  snapshots:
    start: "2019-01-01"
    end: "2020-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2019 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2019-era5

cutout_iberia2019_solar-hsat_q2qv3:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2019_v3.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2019_v3.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2019.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2019.csv
  snapshots:
    start: "2019-01-01"
    end: "2020-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2019 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2019-era5





cutout_iberia2020_solar-hsat_q2qv1:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2020_v1.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2020_v1.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2020.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2020.csv
  snapshots:
    start: "2020-01-01"
    end: "2021-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2020 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2020-era5

cutout_iberia2020_solar-hsat_q2qv2:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2020_v2.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2020_v2.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2020.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2020.csv
  snapshots:
    start: "2020-01-01"
    end: "2021-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2020 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2020-era5

cutout_iberia2020_solar-hsat_q2qv3:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2020_v3.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2020_v3.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2020.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2020.csv
  snapshots:
    start: "2020-01-01"
    end: "2021-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2020 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2020-era5





cutout_iberia2023_solar-hsat_q2qv1:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2023_v1.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2023_v1.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2023.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2023.csv
  snapshots:
    start: "2023-01-01"
    end: "2024-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2023 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2023-era5

cutout_iberia2023_solar-hsat_q2qv2:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2023_v2.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2023_v2.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2023.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2023.csv
  snapshots:
    start: "2023-01-01"
    end: "2024-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2023 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2023-era5

cutout_iberia2023_solar-hsat_q2qv3:
  pypsa_spain:
    q2q_transform:
      enable: true
      onwind: data_ES/q2q/cutout/q2q_onwind_cutout_iberia2023_v3.pkl
      solar-hsat: data_ES/q2q/cutout/q2q_solar-hsat_cutout_iberia2023_v3.pkl
    update_elec_capacities:
      carriers_to_update:
        onwind: data_ES/esios/esios_onwind_capacity_2023.csv
        solar-hsat: data_ES/esios/esios_solar_capacity_2023.csv
  snapshots:
    start: "2023-01-01"
    end: "2024-01-01"
  electricity:
    powerplants_filter: (DateOut >= 2023 or DateOut != DateOut)
  atlite:
    default_cutout: iberia-2023-era5
